### ISSUE TITLE
lets-encrypt-wp-master/lets-encrypt-wp.php on line 13

### ISSUE THREAD

**Issue by WPExpert** [tollmanz/lets-encrypt-wp#4]
I have a problem here ~ I think ~ because I have a non-standard Ubuntu 14.04 LTS server installation. ServerPilot builds their own "deb" packages of Nginx, Apache, and PHP and do not install the versions provided by Ubuntu.

As soon as I try and activate I get a fatal error ~ /public/wp-content/plugins/lets-encrypt-wp-master/lets-encrypt-wp.php on line 13

**Comment by KrissParker** [comment]
Same error as WPExpert.

**Comment by johnbillion** [comment]
Hi folks,

The plugin is currently non-functional while we build it out. We're working on the underlying classes before we turn it into a working plugin.

**Comment by WPExpert** [comment]
I might be wrong, but shouldn't it actually say that somewhere?

**Comment by pbredenberg** [comment]
The readme says this: "Please note that this is an in progress project. It currently does nothing."

**Comment by WPExpert** [comment]
Aha, I was wrong. I sit corrected.
