### ISSUE TITLE
failed to open stream: No such file

### ISSUE THREAD

**Issue by liuxyon** [tollmanz/lets-encrypt-wp#5]
PHP Warning:  require_once(J:\wwwroot\VUSER_Site\WWW\Auto\Seven\wwwroot\wp-content\plugins\lets-encrypt-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in J:\wwwroot\VUSER_Site\WWW\Auto\Seven\wwwroot\wp-content\plugins\lets-encrypt-wp-master\lets-encrypt-wp.php on line 13
PHP Fatal error:  require_once(): Failed opening required 'J:\wwwroot\VUSER_Site\WWW\Auto\Seven\wwwroot\wp-content\plugins\lets-encrypt-wp-master/vendor/autoload.php' (include_path='.;C:\php\pear') in J:\wwwroot\VUSER_Site\WWW\Auto\Seven\wwwroot\wp-content\plugins\lets-encrypt-wp-master\lets-encrypt-wp.php on line 13

**Comment by stevector** [comment]
This project is not ready for use. See https://github.com/tollmanz/lets-encrypt-wp/issues/4
