### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by COLABORATI** [tollmanz/lets-encrypt-wp#8]
Hi, I would like to ask about the status for this project. is there any source of information other than this repo to follow for updates? Thanks!

**Comment by tollmanz** [comment]
Hi @COLABORATI! It's still a work in progress. Following this repo, as well as @tollmanz and @johnbillion on Twitter are your best sources of information. I plan to get back to more active development on this now that the holiday season has passed.

**Comment by COLABORATI** [comment]
Thanks for your info, have a nice start into this year!
