### ISSUE TITLE
Installing lets-encrypt-wp  on Wordpress 4.4.1

### ISSUE THREAD

**Issue by superservidor** [tollmanz/lets-encrypt-wp#9]
I am getting the following erros when I try to activate the plugin lets-encrypt-wp-master.zip (uploaded tho WP using the upload plugin feature):

Warning: require_once(/home/tds/web/tiendadeseguridad.tk/public_html/wp-content/plugins/lets-encrypt-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/tds/web/tiendadeseguridad.tk/public_html/wp-content/plugins/lets-encrypt-wp-master/lets-encrypt-wp.php on line 13

Fatal error: require_once(): Failed opening required '/home/tds/web/tiendadeseguridad.tk/public_html/wp-content/plugins/lets-encrypt-wp-master/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/tds/web/tiendadeseguridad.tk/public_html/wp-content/plugins/lets-encrypt-wp-master/lets-encrypt-wp.php on line 13

**Comment by superservidor** [comment]
I am using WP v4.4.1 under VestaCP

**Comment by stevector** [comment]
See https://github.com/tollmanz/lets-encrypt-wp/issues/4

**Comment by tollmanz** [comment]
Sorry for the troubles @superservidor. The plugin is definitely not ready for primetime at this point. Stay tuned though.
